### ISSUE TITLE
Debugger is missing Python module `google`

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/org.ghidra_sre.Ghidra#86]
How to reproduce:

* Create project and import binary
* In the tool chest, select Debugger
* Click on the bug icon > Configure and launch... > raw gdb

```
GNU gdb (GDB) 14.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/app/lib/ghidra/Ghidra/Debug/Debugger-agent-gdb/pypkg/src/ghidragdb/__init__.py", line 16, in <module>
    from . import util, commands, parameters
  File "/app/lib/ghidra/Ghidra/Debug/Debugger-agent-gdb/pypkg/src/ghidragdb/commands.py", line 23, in <module>
    from ghidratrace.client import Client, Address, AddressRange, TraceObject
  File "/app/lib/ghidra/Ghidra/Debug/Debugger-rmi-trace/pypkg/src/ghidratrace/client.py", line 27, in <module>
    from . import trace_rmi_pb2 as bufs
  File "/app/lib/ghidra/Ghidra/Debug/Debugger-rmi-trace/pypkg/src/ghidratrace/trace_rmi_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ModuleNotFoundError: No module named 'google'
Error while executing Python code.
The target architecture is set to "i386:x86-64".
Undefined command: "ghidra".  Try "help".
Undefined command: "ghidra".  Try "help".
Undefined command: "ghidra".  Try "help".
(gdb) 
```

![image](https://github.com/flathub/org.ghidra_sre.Ghidra/assets/3226457/4831af42-7b53-4463-9383-10872baf8c60)

**Comment by SevaSeva17** [comment]
did you solve this issue? I'm stuck with the same

**Comment by Alexander-Wilms** [comment]
No. I tried installing `google` like this, but that didn't help:

```
      ~  flatpak run --command=sh org.ghidra_sre.Ghidra                                                                                   ✔ 
[📦 org.ghidra_sre.Ghidra ~]$ pip3 install google
Defaulting to user installation because normal site-packages is not writeable
Collecting google
  Downloading google-3.0.0-py2.py3-none-any.whl.metadata (627 bytes)
Collecting beautifulsoup4 (from google)
  Downloading beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting soupsieve>1.2 (from beautifulsoup4->google)
  Downloading soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
Downloading google-3.0.0-py2.py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.3/45.3 kB 2.4 MB/s eta 0:00:00
Downloading beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.9/147.9 kB 6.8 MB/s eta 0:00:00
Downloading soupsieve-2.5-py3-none-any.whl (36 kB)
Installing collected packages: soupsieve, beautifulsoup4, google
Successfully installed beautifulsoup4-4.12.3 google-3.0.0 soupsieve-2.5
```

Adding the wheels to the Flatpak manifest didn't help either, but maybe they just have to installed explicitly.
